#!/bin/bash

# Call this script to build the executable that gets checked into git.

set -uexo pipefail

if [ "xLinux x86_64" -eq "x$(uname -sp)" ]; then echo wrong platform; fi

dist_dir="$(realpath $(dirname $0)/../run)"
cd $(dirname $0)

cargo build --release

cp target/release/vasaplatsen $dist_dir/vasaplatsen
